name: build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install & build
              run: |
                  cp .env.example .env
                  yarn install
                  yarn run lint
              env:
                  CI: true
                  NODE_ENV: development
